services:
  - type: web
    name: recipeverse-backend
    env: python
    buildCommand: "pip install -r requirements.txt && flask --app backend.app db upgrade"
    startCommand: "gunicorn backend.app:app"
    envVars:
      - key: FLASK_APP
        value: backend.app
      - key: SECRET_KEY
        value: your_secret
      - key: OPENAI_API_KEY
        value: your_openai_key
      # ... add all your other environment variables
