services:
  - type: web
    name: recipeverse-backend
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      flask --app backend.app db upgrade
    startCommand: gunicorn backend.app:app
    envVars:
      - key: FLASK_APP
        value: backend.app
      - key: SECRET_KEY
        value: your_secret_key_here
      - key: OPENAI_API_KEY
        value: your_openai_key_here
      - key: STRIPE_API_KEY
        value: your_stripe_key_here
      # Add any other necessary environment variables here